# Production override for docker-compose.yml
version: '3.8'

services:
  mysql:
    restart: always
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=256M

  backend:
    restart: always
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  frontend:
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  admin-dashboard:
    restart: always
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M