version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: everest_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: everest_kitchen
      MYSQL_USER: everest_user
      MYSQL_PASSWORD: everest_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - everest_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: everest_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://everest_user:everest_password@mysql:3306/everest_kitchen
      - JWT_SECRET=your-super-secret-jwt-key-here
      - JWT_EXPIRES_IN=7d
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
      - ADMIN_URL=http://localhost:3001
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - everest_network
    volumes:
      - backend_uploads:/app/uploads
      - backend_logs:/app/logs

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: everest_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - everest_network

  # Admin Dashboard Service
  admin-dashboard:
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile
    container_name: everest_admin
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - everest_network

volumes:
  mysql_data:
  backend_uploads:
  backend_logs:

networks:
  everest_network:
    driver: bridge